apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: workshop/frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: http-port
  selector:
    matchLabels:
      app: frontend
