apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  volumes:
    - name: mongodb-volume-storage
      persistentVolumeClaim:
        claimName: mongodb-volume-claim
  containers:
    - name: mongodb
      image: mongo:4.4-bionic
      ports:
        - containerPort: 27017
          name: mongodb-port
      volumeMounts:
        - name: mongodb-volume-storage
          mountPath: /data/db
